---
- name: Common tasks for all hosts
  hosts: all
  vars:
    ansible_python_interpreter: auto
    girder_virtualenv: "{{ ansible_facts['user_dir'] }}/.virtualenvs/girder3.9"
    worker_virtualenv: "{{ ansible_facts['user_dir'] }}/.virtualenvs/girder3.9"
  tasks:
    - name: Add ssh keys
      authorized_key:
        user: ubuntu
        state: present
        key: "{{ item }}"
      with_file:
        - jon.wain.id_rsa.pub
    - name:  Install deadsnakes
      apt_repository:
        repo: 'ppa:deadsnakes/ppa'
      become: true
      become_user: root
    - name: Install python3.9 and venv
      apt:
       name:
        - python3.9
        - python3.9-venv
       update_cache: yes
      become: true
      become_user: root
    - name: Create virtual environment
      pip:
        name: pip
        version: ">=21.0.1"
        virtualenv: "{{ girder_virtualenv }}"
        virtualenv_command: "/usr/bin/python3.9 -m venv"


- name: Deploy Girder
  hosts: girder
  vars:
    ansible_python_interpreter: auto
    girder_virtualenv: "{{ ansible_facts['user_dir'] }}/.virtualenvs/girder3.9"
  roles:
    - role: girder.mongodb
    - role: girder.girder
    - role: girder.nginx
      vars:
        nginx_hostname: "data.nutritionallungimmunity.org"
        nginx_registration_email: "michael.grauer@kitware.com"
  tasks:
    - name: Install Girder plugins
      pip:
        name:
          - girder-google-analytics
          - git+https://github.com/girder/item_tags.git
          - girder-oauth
          - girder-readme
          - girder-sentry
          - girder-jobs
          - git+https://github.com/NutritionalLungImmunity/girder-nlisim.git
        virtualenv: "{{ girder_virtualenv }}"
        state: latest
      notify:
        - Build Girder web client
        - Restart Girder

    - name: Add celery broker to girder service file
      lineinfile:
        path: "/etc/systemd/system/girder.service"
        line: "Environment=CELERY_BROKER_URL=sqs://"
        regexp: "Environment=CELERY_BROKER_URL=.*"
        state: present
        insertafter: "^\\[Service\\]"
      become: true
      notify:
        - Restart Girder


- name: Deploy worker
  hosts: worker
  vars:
    ansible_python_interpreter: auto
    worker_virtualenv: "{{ ansible_facts['user_dir'] }}/.virtualenvs/girder3.9"
  roles:
    - role: nlisim_worker
      vars:
        worker_virtualenv: "{{ worker_virtualenv }}"
        celery_broker_url: "sqs://"  # keys determined from instance metadata
